// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTrendsRequest) Reset() {
	*x = PostTrendsRequest{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTrendsRequest) ProtoMessage() {}

func (x *PostTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTrendsRequest.ProtoReflect.Descriptor instead.
func (*PostTrendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *PostTrendsRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostTrendsRequest) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type TopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // "likes", "views", "comments"
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *TopRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TopRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Likes         uint32                 `protobuf:"varint,1,opt,name=likes,proto3" json:"likes,omitempty"`
	Views         uint32                 `protobuf:"varint,2,opt,name=views,proto3" json:"views,omitempty"`
	Comments      uint32                 `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStatsResponse) Reset() {
	*x = PostStatsResponse{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStatsResponse) ProtoMessage() {}

func (x *PostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStatsResponse.ProtoReflect.Descriptor instead.
func (*PostStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *PostStatsResponse) GetLikes() uint32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *PostStatsResponse) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PostStatsResponse) GetComments() uint32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type DayStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Likes         uint32                 `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Views         uint32                 `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	Comments      uint32                 `protobuf:"varint,4,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayStats) Reset() {
	*x = DayStats{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayStats) ProtoMessage() {}

func (x *DayStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayStats.ProtoReflect.Descriptor instead.
func (*DayStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *DayStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayStats) GetLikes() uint32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *DayStats) GetViews() uint32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *DayStats) GetComments() uint32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type PostTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trends        []*DayStats            `protobuf:"bytes,1,rep,name=trends,proto3" json:"trends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTrendsResponse) Reset() {
	*x = PostTrendsResponse{}
	mi := &file_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTrendsResponse) ProtoMessage() {}

func (x *PostTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTrendsResponse.ProtoReflect.Descriptor instead.
func (*PostTrendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *PostTrendsResponse) GetTrends() []*DayStats {
	if x != nil {
		return x.Trends
	}
	return nil
}

type PostStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostStats) Reset() {
	*x = PostStats{}
	mi := &file_proto_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostStats) ProtoMessage() {}

func (x *PostStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostStats.ProtoReflect.Descriptor instead.
func (*PostStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{6}
}

func (x *PostStats) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostStats) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostStats           `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_proto_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopPostsResponse) GetPosts() []*PostStats {
	if x != nil {
		return x.Posts
	}
	return nil
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_proto_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{8}
}

func (x *UserStats) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserStats) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserStats           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_proto_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopUsersResponse) GetUsers() []*UserStats {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\x05stats\"&\n" +
	"\vPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\"@\n" +
	"\x11PostTrendsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\":\n" +
	"\n" +
	"TopRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"[\n" +
	"\x11PostStatsResponse\x12\x14\n" +
	"\x05likes\x18\x01 \x01(\rR\x05likes\x12\x14\n" +
	"\x05views\x18\x02 \x01(\rR\x05views\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\rR\bcomments\"f\n" +
	"\bDayStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\rR\x05likes\x12\x14\n" +
	"\x05views\x18\x03 \x01(\rR\x05views\x12\x1a\n" +
	"\bcomments\x18\x04 \x01(\rR\bcomments\"=\n" +
	"\x12PostTrendsResponse\x12'\n" +
	"\x06trends\x18\x01 \x03(\v2\x0f.stats.DayStatsR\x06trends\":\n" +
	"\tPostStats\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\":\n" +
	"\x10TopPostsResponse\x12&\n" +
	"\x05posts\x18\x01 \x03(\v2\x10.stats.PostStatsR\x05posts\":\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\":\n" +
	"\x10TopUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.stats.UserStatsR\x05users2\x88\x02\n" +
	"\fStatsService\x12<\n" +
	"\fGetPostStats\x12\x12.stats.PostRequest\x1a\x18.stats.PostStatsResponse\x12D\n" +
	"\rGetPostTrends\x12\x18.stats.PostTrendsRequest\x1a\x19.stats.PostTrendsResponse\x129\n" +
	"\vGetTopPosts\x12\x11.stats.TopRequest\x1a\x17.stats.TopPostsResponse\x129\n" +
	"\vGetTopUsers\x12\x11.stats.TopRequest\x1a\x17.stats.TopUsersResponseB\vZ\tapi/statsb\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_stats_proto_goTypes = []any{
	(*PostRequest)(nil),        // 0: stats.PostRequest
	(*PostTrendsRequest)(nil),  // 1: stats.PostTrendsRequest
	(*TopRequest)(nil),         // 2: stats.TopRequest
	(*PostStatsResponse)(nil),  // 3: stats.PostStatsResponse
	(*DayStats)(nil),           // 4: stats.DayStats
	(*PostTrendsResponse)(nil), // 5: stats.PostTrendsResponse
	(*PostStats)(nil),          // 6: stats.PostStats
	(*TopPostsResponse)(nil),   // 7: stats.TopPostsResponse
	(*UserStats)(nil),          // 8: stats.UserStats
	(*TopUsersResponse)(nil),   // 9: stats.TopUsersResponse
}
var file_proto_stats_proto_depIdxs = []int32{
	4, // 0: stats.PostTrendsResponse.trends:type_name -> stats.DayStats
	6, // 1: stats.TopPostsResponse.posts:type_name -> stats.PostStats
	8, // 2: stats.TopUsersResponse.users:type_name -> stats.UserStats
	0, // 3: stats.StatsService.GetPostStats:input_type -> stats.PostRequest
	1, // 4: stats.StatsService.GetPostTrends:input_type -> stats.PostTrendsRequest
	2, // 5: stats.StatsService.GetTopPosts:input_type -> stats.TopRequest
	2, // 6: stats.StatsService.GetTopUsers:input_type -> stats.TopRequest
	3, // 7: stats.StatsService.GetPostStats:output_type -> stats.PostStatsResponse
	5, // 8: stats.StatsService.GetPostTrends:output_type -> stats.PostTrendsResponse
	7, // 9: stats.StatsService.GetTopPosts:output_type -> stats.TopPostsResponse
	9, // 10: stats.StatsService.GetTopUsers:output_type -> stats.TopUsersResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
