// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_proto_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int32                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_proto_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostResponse) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int32                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionRequest) Reset() {
	*x = PostActionRequest{}
	mi := &file_proto_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionRequest) ProtoMessage() {}

func (x *PostActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionRequest.ProtoReflect.Descriptor instead.
func (*PostActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_proto_rawDescGZIP(), []int{2}
}

func (x *PostActionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostActionRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        int32                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_proto_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_proto_rawDescGZIP(), []int{3}
}

func (x *CommentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionResponse) Reset() {
	*x = PostActionResponse{}
	mi := &file_proto_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionResponse) ProtoMessage() {}

func (x *PostActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionResponse.ProtoReflect.Descriptor instead.
func (*PostActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_proto_rawDescGZIP(), []int{4}
}

func (x *PostActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_posts_proto protoreflect.FileDescriptor

const file_proto_posts_proto_rawDesc = "" +
	"\n" +
	"\x11proto/posts.proto\x12\x05posts\"@\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"Z\n" +
	"\x12CreatePostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x05R\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"E\n" +
	"\x11PostActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x05R\x06postId\"V\n" +
	"\x0eCommentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x05R\x06postId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\".\n" +
	"\x12PostActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x94\x02\n" +
	"\fPostsService\x12A\n" +
	"\n" +
	"CreatePost\x12\x18.posts.CreatePostRequest\x1a\x19.posts.CreatePostResponse\x12?\n" +
	"\bLikePost\x12\x18.posts.PostActionRequest\x1a\x19.posts.PostActionResponse\x12?\n" +
	"\bViewPost\x12\x18.posts.PostActionRequest\x1a\x19.posts.PostActionResponse\x12?\n" +
	"\vCommentPost\x12\x15.posts.CommentRequest\x1a\x19.posts.PostActionResponseB\vZ\tapi/postsb\x06proto3"

var (
	file_proto_posts_proto_rawDescOnce sync.Once
	file_proto_posts_proto_rawDescData []byte
)

func file_proto_posts_proto_rawDescGZIP() []byte {
	file_proto_posts_proto_rawDescOnce.Do(func() {
		file_proto_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_posts_proto_rawDesc), len(file_proto_posts_proto_rawDesc)))
	})
	return file_proto_posts_proto_rawDescData
}

var file_proto_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_posts_proto_goTypes = []any{
	(*CreatePostRequest)(nil),  // 0: posts.CreatePostRequest
	(*CreatePostResponse)(nil), // 1: posts.CreatePostResponse
	(*PostActionRequest)(nil),  // 2: posts.PostActionRequest
	(*CommentRequest)(nil),     // 3: posts.CommentRequest
	(*PostActionResponse)(nil), // 4: posts.PostActionResponse
}
var file_proto_posts_proto_depIdxs = []int32{
	0, // 0: posts.PostsService.CreatePost:input_type -> posts.CreatePostRequest
	2, // 1: posts.PostsService.LikePost:input_type -> posts.PostActionRequest
	2, // 2: posts.PostsService.ViewPost:input_type -> posts.PostActionRequest
	3, // 3: posts.PostsService.CommentPost:input_type -> posts.CommentRequest
	1, // 4: posts.PostsService.CreatePost:output_type -> posts.CreatePostResponse
	4, // 5: posts.PostsService.LikePost:output_type -> posts.PostActionResponse
	4, // 6: posts.PostsService.ViewPost:output_type -> posts.PostActionResponse
	4, // 7: posts.PostsService.CommentPost:output_type -> posts.PostActionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_posts_proto_init() }
func file_proto_posts_proto_init() {
	if File_proto_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_posts_proto_rawDesc), len(file_proto_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_posts_proto_goTypes,
		DependencyIndexes: file_proto_posts_proto_depIdxs,
		MessageInfos:      file_proto_posts_proto_msgTypes,
	}.Build()
	File_proto_posts_proto = out.File
	file_proto_posts_proto_goTypes = nil
	file_proto_posts_proto_depIdxs = nil
}
